"""init

Revision ID: f8e0f9232e86
Revises: 
Create Date: 2026-01-31 16:03:20.825953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e0f9232e86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('years_in_business', sa.Integer(), nullable=False),
    sa.Column('annual_revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_table('lenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lenders_id'), 'lenders', ['id'], unique=False)
    op.create_table('business_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('paynet_score', sa.Float(), nullable=False),
    sa.Column('trade_line_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_credits_id'), 'business_credits', ['id'], unique=False)
    op.create_table('lender_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=True),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lender_programs_id'), 'lender_programs', ['id'], unique=False)
    op.create_table('loan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('equipment_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_requests_id'), 'loan_requests', ['id'], unique=False)
    op.create_table('personal_guarantors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('fico_score', sa.Integer(), nullable=False),
    sa.Column('has_bankruptcy', sa.Boolean(), nullable=True),
    sa.Column('has_tax_liens', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_guarantors_id'), 'personal_guarantors', ['id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_request_id', sa.Integer(), nullable=True),
    sa.Column('lender_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['lender_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_id'), 'match_results', ['id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['lender_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_id'), 'policy_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_rules_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_match_results_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_personal_guarantors_id'), table_name='personal_guarantors')
    op.drop_table('personal_guarantors')
    op.drop_index(op.f('ix_loan_requests_id'), table_name='loan_requests')
    op.drop_table('loan_requests')
    op.drop_index(op.f('ix_lender_programs_id'), table_name='lender_programs')
    op.drop_table('lender_programs')
    op.drop_index(op.f('ix_business_credits_id'), table_name='business_credits')
    op.drop_table('business_credits')
    op.drop_index(op.f('ix_lenders_id'), table_name='lenders')
    op.drop_table('lenders')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
